### ISSUE TITLE
Zoomed too much, broke something

### ISSUE THREAD

**Issue by PenelopeFudd** [mozilla/seasponge#69] opened 2015-04-02 14:41 UTC
I wanted to zoom in as far as I could, to see what I could see.  After zooming 3 levels, it stopped letting me zoom in, which was expected.  However, the zoom out button didn't do anything.  In fact, most (all?) of the buttons stopped working.  :-)

**Comment by Glavin001** [comment] 2015-04-02 14:55
> In fact, most (all?) of the buttons stopped working. :-)

Sounds like there is an element blocking / in front of those buttons. There are bugs with the zooming (see #34 ) and I think that when you zoomed in that the drawing panel actually overlaid over top of the navigation items and buttons. 

Zooming is still in the works, that is why #34 is not yet closed. Thanks for letting us know!

**Comment by Glavin001** [comment] 2015-04-02 18:26
I'm going to call this a duplicate of #34 , as zooming really is not fully implemented, yet.

**Closed by Glavin001** 2015-04-02 18:26 UTC
Labels: bug
